/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CtrlToogleButton: typeof import('./components/CtrlToogleButton.vue')['default']
    ItemAttrForm: typeof import('./components/ItemAttrForm.vue')['default']
    ItemAttrView: typeof import('./components/ItemAttrView.vue')['default']
    ItemForm: typeof import('./components/ItemForm.vue')['default']
    ItemView: typeof import('./components/ItemView.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stash: typeof import('./components/stash.vue')['default']
  }
}
