/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AffixView: typeof import('./components/AffixView.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    BadgeQuality: typeof import('./components/BadgeQuality.vue')['default']
    CtrlItemAffix: typeof import('./components/CtrlItemAffix.vue')['default']
    CtrlItemQuality: typeof import('./components/CtrlItemQuality.vue')['default']
    CtrlItemType: typeof import('./components/CtrlItemType.vue')['default']
    CtrlSearchAffix: typeof import('./components/CtrlSearchAffix.vue')['default']
    CtrlToogleButton: typeof import('./components/CtrlToogleButton.vue')['default']
    ItemAffix: typeof import('./components/ItemAffix.vue')['default']
    ItemAffixForm: typeof import('./components/ItemAffixForm.vue')['default']
    ItemAffixView: typeof import('./components/ItemAffixView.vue')['default']
    ItemFastCreate: typeof import('./components/ItemFastCreate.vue')['default']
    ItemForm: typeof import('./components/ItemForm.vue')['default']
    ItemQualityBadge: typeof import('./components/ItemQualityBadge.vue')['default']
    ItemView: typeof import('./components/ItemView.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stash: typeof import('./components/stash.vue')['default']
  }
}
